version: 2
jobs:
  pre-build:
    machine: true
    steps:
      - checkout
      - run:
          name: pre-build
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            make build
            make push
  release:
    machine: true
    branches:
      only:
        master
    steps:
      - checkout
      - run:
          name: release
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            make release
