version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: pre-build
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            make build
            make push
