version: 2
jobs:
  release:
    machine: true
    steps:
      - checkout
      - run:
          name: release
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            make release

workflows:
  version: 2
  build-deploy:
    jobs:
      - release:
          filters:
            branches:
              only: master
